Batch database removal (421476)
osisoft/PI-Interface-Rockwell-Factory-Talk-Batch-Docs pull request #55
Opened 2023-06-12 22:19 UTC by KNyce71

Per Ellery Murdock, all instances of PI Batch should be removed from interface guides. The following issues were addressed in this PR for Rockwell Factory Talk:

- **Introduction**  Removed PI Batch Database from Stores bullet point
- **Batch interface overview**: Reworked intro paragraph, deleted buffering paragraph. 
- **Batch interface configuration**: Deleted PI Batch database image
- **How interfaces process batch event data**: Removed variations of PIBatch
- **Recipe templates**: Removed PI Module Database from ModulePath setting
- **Logging and error messages**: Changed log name to Rockwell
- Updated TOC

2023-06-12 22:27 UTC, alan-izar commented on content/installation-prerequisites/installation-prerequisites/logging-and-error-messages.md
> +You can create the Source in the Windows Event Viewer by using the batch interface's source/log name (**PIFTBInt**) before initially starting the interface. After starting the interface, the Windows
Is there a way to use a placeholder here for each interface? This is going to be common text across the interfaces so we'd only need to apply the specific name for each of the logs, unless that's too much work? If so, then this is correct.

2023-06-13 16:14 UTC, KNyce71 commented on content/installation-prerequisites/installation-prerequisites/logging-and-error-messages.md
> +You can create the Source in the Windows Event Viewer by using the batch interface's source/log name (**PIFTBInt**) before initially starting the interface. After starting the interface, the Windows
Yes, in Framework I have set up a placeholder and have a list of the source log names hidden so I can reference them. When I added this topic thru the Framework and went in to modify it, I mistakenly put EMDVB's log name there. User error.

2023-06-13 17:15 UTC, alan-izar commented on content/installation-prerequisites/installation-prerequisites/logging-and-error-messages.md
> +You can create the Source in the Windows Event Viewer by using the batch interface's source/log name (**PIFTBInt**) before initially starting the interface. After starting the interface, the Windows
Got it. Thanks!

2023-06-13 17:16 UTC, alan-izar approved these changes

2023-06-13 17:17 UTC, alan-izar requested changes

2023-06-13 17:17 UTC, alan-izar commented on content/how-batch-interfaces-work/templates-for-mapping-data-source-events/recipe-templates.md
> +    **MODULEPATH** | (Optional) For unit procedures (level 2) or phase (level 4), specifies where the recipe resides in the PI AF element hierarchy. In the Module Database, the path specifies the loc
~In the Module Database, the path specifies the location of the PIUnit for the unit batch.~

2023-06-13 17:17 UTC, alan-izar approved these changes

2023-06-13 17:18 UTC, alan-izar requested changes

2023-06-13 17:18 UTC, alan-izar commented on content/introduction/introduction.md
> +* **Stores** the collected data as event frames and elements within a supported database (PI Asset Framework (PI AF) Database).
feels a little redundant. Maybe 

**Stores** the collected data as event frames and elements within a PI Asset Framework (PI AF) Database.

2023-06-13 17:18 UTC, alan-izar approved these changes

2023-06-13 21:42 UTC, KNyce71 commented on content/how-batch-interfaces-work/templates-for-mapping-data-source-events/recipe-templates.md
> +    **MODULEPATH** | (Optional) For unit procedures (level 2) or phase (level 4), specifies where the recipe resides in the PI AF element hierarchy. In the Module Database, the path specifies the loc
Done

2023-06-13 21:42 UTC, KNyce71 commented on content/introduction/introduction.md
> +* **Stores** the collected data as event frames and elements within a supported database (PI Asset Framework (PI AF) Database).
Done

2023-06-13 21:43 UTC, merged